---
title: "Report"
author: "Francisco"
date: "2024-07-14"
output: html_document
---
## Installing and loading necessary packages for importing and cleaning data
```{r}
install.packages("tidyverse", repos="http://cran.us.r-project.org")
install.packages("janitor", repos="http://cran.us.r-project.org")
install.packages("here",repos="http://cran.us.r-project.org")
install.packages("skimr", repos="http://cran.us.r-project.org")
install.packages("ggplot2", repos="http://cran.us.r-project.org")
install.packages("lubridate", repos="http://cran.us.r-project.org")
install.packages("scales", repos="http://cran.us.r-project.org")
library(tidyverse)
library(janitor)
library(here)
library(skimr)
library(ggplot2)
library(lubridate)
library(scales)
```
## Importing merged csv file
```{r}
twelve_months_data <- read_csv("~/Data Analysis/Certificado Google/Estudo de Caso - Cyclistic/Original Datasets/CSV files/merged.csv")
```
## Checking data integrity and structure
```{r}
colnames(twelve_months_data)
str(twelve_months_data)
View(twelve_months_data)
```
## Omitting entries with missing values and removing duplicates
```{r}
clean_twelve_months_data <- na.omit(twelve_months_data) %>% distinct(ride_id, .keep_all = TRUE)
```
## Creating new columns for analysis
```{r}
year_data_with_new_columns <- clean_twelve_months_data %>% mutate(ride_length = ended_at - started_at, day_of_week = weekdays(started_at)) %>% filter(ride_length > 0) %>% clean_names() 
```
##Exporting .csv file
```{r}
write_csv(year_data_with_new_columns, "cleandata.csv")
```
